name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: |
            set -o pipefail
            swiftlint
            
    - name: Build
      run: |
            set -o pipefail
            swift build
    - name: Run tests
      run: |
            set -o pipefail
            swift test
